apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-cjlh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0039-tenant/tkrw-pr712-0075-0039-app/devfile-sample-cjlh@sha256:edc106b7dd7a344be0cdac48c8daa1fc5a73b66b324f23372fb0b177d858a027
        name: my-nodejs
        resources: {}
status: {}
